### ISSUE TITLE
[Epic] Hathor Explorer Q3/21

### ISSUE THREAD

**Issue by giovanecosta** [HathorNetwork/hathor-explorer-service#25]
# Introduction

This epic will manage 2 projects, hathor-explorer and hathor-explorer-service both serving as frontend and backend for Hathor Explorer website.

An explorer is a website that displays information on the DAG (and blockchain) with a clean and clear UI.

# Motivation

The idea behind this website is to have a simple and user friendly interface for users to check whats happening on the DAG, check transactions, tokens, network statistics, etc. so that any user with no technical expertise can access these informations.

A common expected use is to create a link with the transaction id and any one can view the information on said transaction without having to run a node or calling a public node api, which could create a lot of unnecessary stress on public nodes.

# Acceptance criteria

Having a highly scalable website with fast load time and mitigating all access to a full-node.
Expose any and all information a full-node has available with a clear UX/UI and network aggregated data with close to real-time delays (as much as posible).

# Planning

Old Planning Spreadsheet: https://docs.google.com/spreadsheets/d/1VKWD2gENqfUSrl1eSnD25hNtVnBX4RzJJ88mxflHHeM/edit?usp=sharing

# Q2 Spill Over ([Epic](https://github.com/HathorNetwork/hathor-explorer-service/issues/6))

## Tasks
- **Hathor Explorer Service**
    - [ ] #19
    - [x] #39
- **Hathor Explorer**
    - [ ] [Show Aggregated Data on Network Page](https://github.com/HathorNetwork/hathor-explorer-service/issues/19)

### Features
:hourglass_flowing_sand: New Network Page

# July 2021

## Tasks
- **Hathor Explorer Service**
    - [ ] #40
    - [x] #28
    - [x] #39 
- **Hathor Explorer**
    - [ ] HathorNetwork/hathor-explorer#83
    - [ ] HathorNetwork/hathor-explorer#84
- **Hathor Wallet**
    - [ ] HathorNetwork/hathor-wallet#209 (Start discussion)

### Features
:hourglass_flowing_sand: Highlighted Tokens
:hourglass_flowing_sand: Scam Tokens
:hourglass_flowing_sand: Verified Tokens
:hourglass_flowing_sand: Transaction Metadata

## Tasks
- **Hathor Explorer Service**
    - [ ] #41
- **Hathor Explorer** 
    - [ ] HathorNetwork/hathor-explorer#89

### Features
:hourglass_flowing_sand: Receive User Reports for Token

## Tasks
- **Hathor Explorer Service**
    - [ ] #50
- **Hathor Explorer** 
    - [ ] HathorNetwork/hathor-explorer#90
    - [ ] HathorNetwork/hathor-explorer#91
- **Hathor Wallet Service**
    - [ ] HathorNetwork/hathor-wallet-service#106

### Features
:sparkles: Filter and Paginate Token List
:sparkles: Filter Token by Type

## Tasks
- **Hathor Explorer** 
    - [ ] Change Decode Tx to use `hathor-lib` instead of API call

### Features
:sparkles: Decode Transaction in Browser

## Tasks
- **Hathor Explorer Service**
    - [ ] Transactions API
- **Hathor Explorer** 
    - [ ] Change Transactions Page to new API
- **Hathor Wallet Service**
    - [ ] List Transactions

### Features
:sparkles: Latest Blocks/Transactions

## Tasks
- **Hathor Explorer Service**
    - [ ] Statistics Collector
    - [ ] Statistics API
- **Hathor Explorer** 
    - [ ] Change Statistics Page to new API

### Features
:sparkles: Statistics Page

## Tasks
- **Hathor Explorer** 
    - [ ] Remove DAG Page

### Features
:sparkles: Remove DAG Page

## Tasks
- **Hathor Explorer Service**
    - [ ] Fetch and cache Peer Location on Data Aggregator 
- **Hathor Explorer** 
    - [ ] Show Peer Location on Map in Network Page

### Features
:sparkles: P2P World Map

## Tasks
- **Hathor Explorer**
    - [ ] Add Tests
    - [ ] Extract Business Functions
    - [ ] Break Pages into Components

### Features
:sparkles: UI Refactor - Part I

# August 2021

## Tasks
- **Hathor Explorer Service**
    - [ ] Save Data From Statistics Collector on Database
    - [ ] Collect and Save Number of Tokens and Transactions
    - [ ] Collect and Save Economics Information 
    - [ ] Add Hashrate History on Statistics API
    - [ ] Add Number of Tokens and Transactions History on Statistics API
    - [ ] Add Economics History on Statistics API
- **Hathor Explorer** 
    - [ ] Show Hashrate Graph Over Time on Statistics Page
    - [ ] Show Number of Token and Transactions Graph Over Time on Statistics Page
    - [ ] Show Economics Info Over Time on Statistics Page
    - [ ] Create Dashboard Page with Hot Info about Economics and Statistics

### Features
:sparkles: Hashrate Over Time
:sparkles: Number of Peers Over Time
:sparkles: Number of Tokens Over Time
:sparkles: Number of Transactions Over Time
:sparkles: Economics Information (total supply, circulating supply, pre-mine released, mined supply)

## Tasks
- **Hathor Explorer**
    - [ ] Add Halving Calculation
    - [ ] Create Halving Countdown Page

### Features
:sparkles: Halving Countdown Page

## Tasks
- **Hathor Explorer Service**
    - [ ] Address API
- **Hathor Explorer** 
    - [ ] Show Richest Addresses on Statistics Page
    - [ ] Show Quantity of HTR Deposited Over Time on Dashboard
- **Hathor Wallet Service**
    - [ ] Add Richest Addresses info on API
    - [ ] Add Quantity of HTR Deposited info on API

### Features
:sparkles: Hathor Richest Addresses
:sparkles: Richest addresses for a given Token
:sparkles: Quantity of HTR Deposited for Token Creation Over Time

## Tasks
- **Hathor Explorer**
    - [ ] Add i18n and portuguese transalation
    - [ ] Implement Design System

### Features 
:sparkles: Translation
:sparkles: UI Refactor - Part II

# September 2021

TBD

**Comment by giovanecosta** [comment]
# Jul 5th - 9th

## Tasks
- **Hathor Explorer Service**
    - [ ] [Network Data Aggregator](https://github.com/HathorNetwork/hathor-explorer-service/issues/19)
    - [ ] Metadata API

- **Hathor Explorer**
    - [ ] [Show Aggregated Data on Network Page](https://github.com/HathorNetwork/hathor-explorer-service/issues/19)
    - [ ] Show Info in Transaction Page
    - [ ] Show Info in Token Page

### Features
- New Network Page
- Highlighted Tokens
- Scam Tokens
- Verified Tokens
- Transaction Metadata

**Comment by giovanecosta** [comment]
# Jul 12th - 16th

## Tasks
- **Hathor Explorer Service**
    - [ ] Report API
    - [ ] Token API
- **Hathor Explorer** 
    - [ ] Report Form in Token Page
    - [ ] Paginate Token List
    - [ ] Filter Token List
- **Hathor Wallet Service**
    - [ ] List Token

### Features
:sparkles: Filter and Paginate Token List
:sparkles: Filter Token by Type
:sparkles: Receive User Reports for Token

**Comment by giovanecosta** [comment]
# Week 29 (Jul 19th - 23th)

## Spill Over
- **Hathor Explorer Service**
    - [ ] #19 
    - [ ] #40 
    - [ ] #28 

- **Hathor Explorer**
    - [ ] [Show Aggregated Data on Network Page](https://github.com/HathorNetwork/hathor-explorer-service/issues/19)
    - [ ] HathorNetwork/hathor-explorer#83
    - [ ] HathorNetwork/hathor-explorer#84
- **Hathor Wallet**
    - [ ] HathorNetwork/hathor-wallet#209 (Start discussion)

- **Hathor Explorer Service**
    - [ ] #41 
    - [ ] Token API
- **Hathor Explorer** 
    - [ ] Report Form in Token Page
    - [ ] Paginate Token List https://github.com/HathorNetwork/hathor-explorer/issues/61
    - [ ] Filter Token List
- **Hathor Wallet Service**
    - [ ] List Token

### Features
:hourglass_flowing_sand: New Network Page
:hourglass_flowing_sand: Highlighted Tokens
:hourglass_flowing_sand: Scam Tokens
:hourglass_flowing_sand: Verified Tokens
:hourglass_flowing_sand: Transaction Metadata
:hourglass_flowing_sand: Filter and Paginate Token List
:sparkles: Filter Token by Type
:hourglass_flowing_sand: Receive User Reports for Token

**Comment by giovanecosta** [comment]
# Week 30 (Jul 26th - 30th)

## Spill Over
- **Hathor Explorer Service**
    - [ ] #19 
    - [ ] #40 
    - [ ] #41 
    - [ ] #50
    - [ ] #39
- **Hathor Explorer**
    - [ ] [Show Aggregated Data on Network Page](https://github.com/HathorNetwork/hathor-explorer-service/issues/19)
    - [ ] HathorNetwork/hathor-explorer#83
    - [ ] HathorNetwork/hathor-explorer#84
    - [ ] HathorNetwork/hathor-explorer#90
    - [ ] HathorNetwork/hathor-explorer#91
- **Hathor Wallet**
    - [ ] HathorNetwork/hathor-wallet#209 (Start discussion)
- **Hathor Wallet Service**    
    - [ ] HathorNetwork/hathor-wallet-service#106

## Tasks
- **Hathor Explorer**
    - [ ] Change Decode Tx to use hathor-lib instead of API call

### Features
:hourglass_flowing_sand: New Network Page
:hourglass_flowing_sand: Highlighted Tokens
:hourglass_flowing_sand: Scam Tokens
:hourglass_flowing_sand: Verified Tokens
:hourglass_flowing_sand: Transaction Metadata
:hourglass_flowing_sand: Filter and Paginate Token List
:hourglass_flowing_sand: Filter Token by Type
:hourglass_flowing_sand: Receive User Reports for Token
:hourglass_flowing_sand: Decode Transaction in Browser

**Comment by giovanecosta** [comment]
# Week 31 (Ago 2nd - 6th)

## Spill Over
- **Hathor Explorer Service**
    - [ ] #19 
    - [ ] #40 
    - [ ] #41 
    - [ ] #50
- **Hathor Explorer**
    - [ ] [Show Aggregated Data on Network Page](https://github.com/HathorNetwork/hathor-explorer-service/issues/19)
    - [ ] HathorNetwork/hathor-explorer#83
    - [ ] HathorNetwork/hathor-explorer#84
    - [ ] HathorNetwork/hathor-explorer#90
    - [ ] HathorNetwork/hathor-explorer#91
    - [ ] Change Decode Tx to use hathor-lib instead of API call
- **Hathor Wallet**
    - [ ] HathorNetwork/hathor-wallet#209 (Start discussion)
- **Hathor Wallet Service**    
    - [ ] HathorNetwork/hathor-wallet-service#106

### Features

:hourglass_flowing_sand: Highlighted Tokens
:hourglass_flowing_sand: Scam Tokens
:hourglass_flowing_sand: Verified Tokens
:hourglass_flowing_sand: Transaction Metadata
:hourglass_flowing_sand: Filter and Paginate Token List
:hourglass_flowing_sand: Filter Token by Type
:hourglass_flowing_sand: Receive User Reports for Token
:hourglass_flowing_sand: Decode Transaction in Browser

**Comment by giovanecosta** [comment]
# Week 32 (Ago 9th - 13th)

## Spill Over
- **Hathor Explorer Service**
    - [ ] #19 
    - [ ] #40 
    - [ ] #41 
    - [ ] #50
- **Hathor Explorer**
    - [ ] [Show Aggregated Data on Network Page](https://github.com/HathorNetwork/hathor-explorer-service/issues/19)
    - [ ] HathorNetwork/hathor-explorer#83
    - [ ] HathorNetwork/hathor-explorer#84
    - [ ] HathorNetwork/hathor-explorer#90
    - [ ] HathorNetwork/hathor-explorer#91
    - [ ] HathorNetwork/hathor-explorer#101
- **Hathor Wallet**
    - [ ] HathorNetwork/hathor-wallet#209 (Start discussion)
- **Hathor Wallet Service**    
    - [ ] HathorNetwork/hathor-wallet-service#106

### Features

:hourglass_flowing_sand: Highlighted Tokens
:hourglass_flowing_sand: Scam Tokens
:hourglass_flowing_sand: Verified Tokens
:hourglass_flowing_sand: Transaction Metadata
:hourglass_flowing_sand: Filter and Paginate Token List
:hourglass_flowing_sand: Filter Token by Type
:hourglass_flowing_sand: Receive User Reports for Token
:hourglass_flowing_sand: Decode Transaction in Browser

**Comment by r4mmer** [comment]
# Ago 30th - Sep 3rd

## Tasks
- **Hathor Explorer Service**
    - [PARTIAL] #67 
    - [PARTIAL] #65 
    - [PARTIAL] #66 
- **Hathor Explorer**
    - [PARTIAL] HathorNetwork/hathor-explorer#116

### Features

:hourglass_flowing_sand: Dag Metadata API

**Comment by r4mmer** [comment]
# Sep 6th - 10rd

## Tasks
- **Hathor Explorer Service**
    - [x] #67 
    - [x] #65 
    - [PARTIAL] #66
    - [PARTIAL] #75 
- **Hathor Explorer**
    - [x] HathorNetwork/hathor-explorer#116

### Features

:heavy_check_mark: Dag Metadata API
:hourglass_flowing_sand: Network Data aggregator
