### ISSUE TITLE
[EPIC] Hathor Explorer Service

### ISSUE THREAD

**Issue by giovanecosta** [HathorNetwork/hathor-explorer-service#6]
- [ ] [Main Design](https://github.com/HathorNetwork/hathor-explorer/pull/52)
- [ ] [Data Collector](https://github.com/HathorNetwork/hathor-explorer-service/pull/3)
- [ ] [Token Metadata]()
- [ ] Data Aggregator
- [ ] Network Handler

**Comment by giovanecosta** [comment]
# May 24th - May 28th
- [ ] [Partial] Hathor Explorer V1: Implement Network API.
- [ ] [KTLO] Whitelist/blacklist tokens and transactions.
    - [ ] Backend: Token Metadata
    - [ ] Explorer
    - [ ] Wallets
- [ ] [Partial][KTLO] Hathor Explorer: Token details for a NFT. 
- [ ] Hathor Explorer V2: Compile data and discuss the next steps.
- [ ] Hathor Explorer V1: Network API aggregated data POC.
- [ ] Hathor Explorer V1: Implement Network API aggregated data.

**Comment by giovanecosta** [comment]
# May 31st - Jun 4th
- [x] Hathor Explorer V1: Implement Network API. (Review and deploy)
- [ ] [KTLO] Whitelist/blacklist tokens and transactions.
    - [ ] Backend: Token Metadata
    - [ ] Explorer
    - [ ] Wallets
- [x] [KTLO] Hathor Explorer: Token details for a NFT. (Finish refactor and deploy) 
- [ ] Hathor Explorer V2: Compile data and discuss the next steps.

**Comment by giovanecosta** [comment]
# Jun 7th - Jun 11th
- [x] [Token Metadata](https://github.com/HathorNetwork/hathor-explorer-service/pull/7)
- [x] [NFT Preview Page](https://github.com/HathorNetwork/hathor-explorer/pull/54)

**Comment by giovanecosta** [comment]
# Jun 14th - Jun 18th
- [ ] [Explorer v2 thoughts data compiled](https://github.com/HathorNetwork/hathor-explorer-service/issues/12)
- [ ] [Network Page](https://github.com/HathorNetwork/hathor-explorer/issues/73)
- [ ] [NFT Preview Audio File](https://github.com/HathorNetwork/hathor-explorer-service/issues/20)

**Comment by giovanecosta** [comment]
# Jun 21th - Jun 25th
- [ ] First GDPR message on explorer.
- [ ] CORS on explorer service
- [ ] Statistics collector

**Comment by giovanecosta** [comment]
# Jun 28th - Jul 2nd
- [ ] [Data Aggregator Implementation](https://github.com/HathorNetwork/hathor-explorer-service/issues/19)
